apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ethstats
  labels:
    app: ethstats
    chart: ethstats
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  WS_SECRET: {{ .Values.ethstats.webSocketSecret | b64enc | quote }}
