kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-ethstats
  labels:
    app: ethstats
    chart: ethstats
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: ethstats
spec:
  selector:
    app: ethstats
    release: {{ .Release.Name }}
    component: ethstats
  type: {{ .Values.ethstats.service.type }}
  ports:
  - port: 80
    targetPort: http
