apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ethstats-ingress
  labels:
    app: ethstats
    chart: ethstats
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: ethstats
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - {{ .Release.Name }}-ethstats.{{ .Values.domain.name }}.org
    secretName: {{ .Release.Name }}-ethstats-tls
  rules:
  - host: {{ .Release.Name }}-ethstats.{{ .Values.domain.name }}.org
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-ethstats
          servicePort: 80
